---
# this playbook installs the desired user packages 

- name: Update packages
  command: arch-chroot /mnt pacman -Syu

- name: Install packages
  command: "arch-chroot /mnt pacman -S {{ pacman_package_list + host_pacman_package_list | join(' ') }} --noconfirm"
