---
# this playbook chroots into the new environment

- name: Generate fstab
  command: genfstab -U /mnt >> /mnt/etc/fstab

- name: Chroot into environment
  command: arch-chroot /mnt

- name: Set timezone
  command: ln -sf /usr/share/zoneinfo/America/Toronto /etc/localtime

- name: Set hardware clock
  command: hwclock --systohc

- name: Set locale
  command: sed -i "/{{locale}}/s/^#//g"

- name: Generate 'locale.conf'
  command: echo "LANG={{ locale }}" > /etc/locale.conf

- name: Set hostname
  command: echo {{ hostname }} > /etc/hostname
