---
hostname: "spire"

install_drive: /dev/nvme0n1

partitions:
  boot:
    location: "/boot"
    part_start: "1MiB"
    part_end: "301MiB"
  swap:
    part_start: "301MiB"
    part_end: "16.3GiB"
  root:
    location: "/"
    part_start: "16.3GiB"
    part_end: "300.3GiB"
  home:
    location: "/home"
    part_start: "300.3GiB"
    part_end: "100%"

i3_font_size: 22

i3_exec_extra:
  - udiskie &
  - xscreensaver &
  - moolticuted &

i3blocks_disks:
  - { label: "boot", disk: "/boot" }
  - { label: "root", disk: "/" }
  - { label: "home", disk: "/home" }

host_pacman_package_list:
  - sof-firmware
