---
hostname: "spire"

install_drive: /dev/nvme0n1

partitions:
  boot:
    location: "/boot"
    part_start: "1MiB"
    part_end: "301MiB"
  swap:
    part_start: "301MiB"
    part_end: "16GiB"
  root:
    location: "/"
    part_start: "16GiB"
    part_end: "300GiB"
  home:
    location: "/home"
    part_start: "300GiB"
    part_end: "100%"

kernel_params:
  - fbcon=rotate:1
  - video=DSI-1:panel_orientation=right_side_up

i3_font_size: 20

i3_exec_extra:
  - udiskie &
  - xscreensaver &
  - moolticuted &

i3blocks_disks:
  - { label: "boot", disk: "/boot" }
  - { label: "root", disk: "/" }
  - { label: "home", disk: "/home" }

host_pacman_package_list:
  - sof-firmware

#host_aur_package_list:
#host_init_commands:
