---
hostname: "virtual"

install_drive: /dev/sda

partitions:
  boot:
    location: "/boot"
    part_start: "1MiB"
    part_end: "301MiB"
  swap:
    part_start: "301MiB"
    part_end: "2.3GiB"
  root:
    location: "/"
    part_start: "2.3GiB"
    part_end: "12.3GiB"
  home:
    location: "/home"
    part_start: "12.3GiB"
    part_end: "100%"

i3_font_size: 24
i3_exec_extra:
  - exec udiskie &
  - exec xscreensaver &
  - exec nm-applet &
  #- exec optimus-manager-qt &
i3blocks_disks:
  - { label: "boot", disk: "/boot" }
  - { label: "root", disk: "/root" }
